FROM golang:1.21-alpine3.18 as builder
WORKDIR /app
ADD . /app
ENV GOOS=linux GOARCH=arm64 CGO_ENABLED=0
RUN go env -w GOPROXY=https://goproxy.cn && mkdir -p release/linux/arm64 && go build -o release/linux/arm64/plugin .

FROM alpine:3.18
ENV GODEBUG netdns=go

COPY --from=builder /app/release/linux/arm64/plugin /bin

ENTRYPOINT ["/bin/plugin"]